Fetch In React Practice
htjahyon/m3-0321-code-solutions pull request #22
Opened 2021-04-07 00:54 UTC by htjahyon

![image](https://user-images.githubusercontent.com/68126492/113795101-f1f39a00-9700-11eb-923f-e2d28e39f79a.png)

2021-04-07 02:12 UTC, scbowler requested changes
I noticed in your picture you opened your project through the file system, the project won't function properly like that. You need to use `npm run dev` to start your servers, then go to `localhost:3000` in your browser to view and test the project. A couple updates needed around how state is being handled, see below comments. Let me know if you have any questions.

2021-04-07 02:12 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +      .then(data => this.state.todos.push(newTodo))
Here you can't directly push the new todo to state. You need to copy the todos array, add the new todo item, and then setState.

2021-04-07 02:12 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +    const notCompleted = !this.state.todos[todoId].isCompleted;
The todoId is not the same as its index, so you actually need to use something like `.findIndex` here to get the index of the todo with the supplied todoId

2021-04-07 02:12 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +      .then(res => res.json())
You need to update state with the object returned from making the PATCH request, and the index of the updated todo item from above.

2021-04-07 04:02 UTC, scbowler requested changes
Your handling of state looks much better! Only remaining issue is the urls you are using in your fetch requests, I'm sure you did that in relation to the issues you are having getting the project to work properly.

2021-04-07 04:02 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +    fetch('https://localhost:3000/api/todos', {
You don't want to include the full localhost and port in your URL, this will cause issues when you deploy your application to the internet. should just be:

```JSX
fetch('/api/todos`)
```

2021-04-07 04:02 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +    fetch('https://localhost:3000/api/todos', {
Should be `/api/todos`

2021-04-07 04:02 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +    fetch(`https://localhost:3000/api/todos/${todoId}`, {
Should be `/api/todos/${todoId}`

2021-04-08 20:47 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/114094157-d3acac00-9870-11eb-9373-eba8bb0174e0.png))
![image](https://user-images.githubusercontent.com/68126492/114094212-e4f5b880-9870-11eb-9ed4-27f6a7925877.png)

2021-04-08 20:53 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/114094845-a280ab80-9871-11eb-8e90-3f5285240f27.png)
![image](https://user-images.githubusercontent.com/68126492/114095058-d8259480-9871-11eb-9816-849a80d9fe96.png)

2021-04-08 23:13 UTC, scbowler approved these changes
Great job implementing the feedback. Looks good! 👍

2021-04-08 23:36 UTC, merged