API Authentication
htjahyon/m3-0321-code-solutions pull request #25
Opened 2021-04-14 01:55 UTC by htjahyon

![image](https://user-images.githubusercontent.com/68126492/114642995-b5d4b200-9c89-11eb-918c-d91c7dba7bbb.png)

2021-04-14 02:14 UTC, scbowler requested changes
Some updates needed, see below comments for details. Let me know if you have any questions.

2021-04-14 02:14 UTC, scbowler commented on api-authentication/server/index.js
> +        where "hashedPassword" = $2
You want to get the user by their `username`, should be `username = $1`

2021-04-14 02:14 UTC, scbowler commented on api-authentication/server/index.js
> +        returning "userId", "username", "password"`;
You don't need a `returning` on a `select` statement, that is only for `insert` and `update`

2021-04-14 02:14 UTC, scbowler commented on api-authentication/server/index.js
> +  const params = [userId, usernameData, hashedPasswordData];
The only param you need in your array is the user's `username`

2021-04-14 02:14 UTC, scbowler commented on api-authentication/server/index.js
> +    .catch(err => next(err));
You need to query the database first to get the `hashedPassword` from the database. Then you use `.verify` to compare the `hashedPassword` to the `password` the user sent to the endpoint.

2021-04-16 02:21 UTC, htjahyon commented
![image](https://user-images.githubusercontent.com/68126492/114962586-cf0f6700-9e1f-11eb-8dd8-5026a51deaca.png)

2021-04-16 02:22 UTC, scbowler approved these changes
Great job implementing the feedback! Looks great! 👍

2021-04-16 02:24 UTC, merged